name: x64 Linux Build
on: workflow_dispatch
jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-20.04 # Distro with at least an suitable GLibC version
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # IMPORTANT!

      - name: Restore Cache Files
        id: restore-cache
        uses: actions/cache@v4.0.2
        with:
          path: |
            .haxelib
            export/release/linux/haxe
            export/release/linux/obj
          key: funkin-cache-linux

      - name: Setup Haxe environment
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install VLC dependencies
        run: |
            sudo apt-get update
            sudo apt-get install libvlc-dev libvlccore-dev

      - name: Setup Haxe libraries
        run: |
           haxelib --quiet install hmm
           haxelib --quiet run hmm setup
           haxelib --quiet run hmm reinstall

      - name: Build Game
        run: haxelib run lime build linux

      - name: Add Executable Privileges
        run: chmod +x export/release/linux/bin/Funkin

      - name: Upload!
        uses: actions/upload-artifact@v4
        with:
          name: linuxBuild
          path: export/release/linux/bin
          if-no-files-found: error

      - name: Save Compiled Data
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            .haxelib
            export/release/linux/haxe
            export/release/linux/obj
          key: funkin-cache-linux
